[supervisord]
nodaemon=true

[program:master]
command=uvicorn nap.master.asgi:APP --port 8000
directory=nap-backend
autostart=true
autorestart=true
environment=LOG.FILE="logs/nap-master.log"

[program:knowledge]
command=uvicorn nap.knowledge.asgi:APP --port 8001
directory=nap-backend
autostart=true
autorestart=true
environment=LOG.FILE="logs/nap-knowledge.log"


; [program:frontend]
; command=npm -C nap-frontend run dev
; autostart=true
; autorestart=true
; environment=LOG.FILE="logs/nap-knowledge.log"
